In [84]:
import numpy as np
from numpy.linalg import norm
import os
from math import floor

test_str = """#.##..##.
..#.##.#.
##......#
##......#
..#.##.#.
..##..##.
#.#.##.#."""
second_str = """#...##..#
#....#..#
..##..###
#####.##.
#####.##.
..##..###
#....#..#"""

In [43]:
arr_str = [list(s.replace('.', '0').replace('#', '1')) for s in test_str.split("\n")]
another_arr_str = [list(s.replace('.', '0').replace('#', '1')) for s in second_str.split("\n")]
arr_num = np.asarray(arr_str, dtype=np.int16)
another_arr_num = np.asarray(another_arr_str, dtype=np.int16)
arr_num

array([[1, 0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 0, 1, 0]], dtype=int16)

In [35]:
norm(arr_num, axis=0, ord=1)

array([4., 2., 5., 2., 3., 3., 2., 5., 2.])

In [36]:
norm(arr_num, axis=1, ord=1)

array([5., 4., 3., 3., 4., 4., 5.])

In [63]:
norm(arr_num.T, axis=0, ord=1)

array([5., 4., 3., 3., 4., 4., 5.])

In [28]:
np.matmul(arr_num, arr_num.T)

array([[5, 2, 1, 1, 2, 4, 3],
       [2, 4, 0, 0, 4, 2, 4],
       [1, 0, 3, 3, 0, 0, 1],
       [1, 0, 3, 3, 0, 0, 1],
       [2, 4, 0, 0, 4, 2, 4],
       [4, 2, 0, 0, 2, 4, 2],
       [3, 4, 1, 1, 4, 2, 5]], dtype=int16)

In [37]:
np.matmul(arr_num, arr_num.T) - norm(arr_num, axis=1, ord=1)

array([[ 0., -2., -2., -2., -2.,  0., -2.],
       [-3.,  0., -3., -3.,  0., -2., -1.],
       [-4., -4.,  0.,  0., -4., -4., -4.],
       [-4., -4.,  0.,  0., -4., -4., -4.],
       [-3.,  0., -3., -3.,  0., -2., -1.],
       [-1., -2., -3., -3., -2.,  0., -3.],
       [-2.,  0., -2., -2.,  0., -2.,  0.]])

In [40]:
np.matmul(arr_num.T, arr_num) - norm(arr_num, axis=0, ord=1)

array([[ 0.,  0., -3., -1., -2., -2., -1., -3.,  0.],
       [-2.,  0., -5., -2., -3., -3., -2., -5.,  0.],
       [-2., -2.,  0.,  0.,  0.,  0.,  0.,  0., -2.],
       [-3., -2., -3.,  0., -3., -3.,  0., -3., -2.],
       [-3., -2., -2., -2.,  0.,  0., -2., -2., -2.],
       [-3., -2., -2., -2.,  0.,  0., -2., -2., -2.],
       [-3., -2., -3.,  0., -3., -3.,  0., -3., -2.],
       [-2., -2.,  0.,  0.,  0.,  0.,  0.,  0., -2.],
       [-2.,  0., -5., -2., -3., -3., -2., -5.,  0.]])

In [51]:
(np.matmul(another_arr_num, another_arr_num.T) - norm(another_arr_num, axis=1, ord=1))

array([[ 0.,  0., -4., -5., -5., -4.,  0.],
       [-1.,  0., -4., -6., -6., -4.,  0.],
       [-3., -2.,  0., -3., -3.,  0., -2.],
       [-2., -2., -1.,  0.,  0., -1., -2.],
       [-2., -2., -1.,  0.,  0., -1., -2.],
       [-3., -2.,  0., -3., -3.,  0., -2.],
       [-1.,  0., -4., -6., -6., -4.,  0.]])

In [56]:
tmp = (np.matmul(another_arr_num, another_arr_num.T) - norm(another_arr_num, axis=1, ord=1))

In [58]:
np.trace(np.flipud(tmp[1:, 1:]))

0.0

In [61]:
a = """abc
cde
efg

aaa
bbb
ccc
"""
a.split(2 * os.linesep)[0].split("\n")

['abc', 'cde', 'efg']

In [65]:
arr_num.shape[0] + 1

8

In [91]:
for i in range(-tmp.shape[0] + 2, tmp.shape[0] - 1):
    diag_tmp = np.diag(np.flipud(tmp), i)
    if len(diag_tmp) % 2 == 0:
        if i <= 0:
            start, end = 0, len(diag_tmp) - 1
        else:
            start, end = i, another_arr_num.shape[0] - 1 
        cutoff_point = floor((start + end) / 2)
        print(f"{diag_tmp = }, {i = }, {start = }, {end = }, {cutoff_point = }")

diag_tmp = array([-1.,  0.]), i = -5, start = 0, end = 1, cutoff_point = 0
diag_tmp = array([-2., -2., -4., -5.]), i = -3, start = 0, end = 3, cutoff_point = 1
diag_tmp = array([-3., -2., -1., -3., -6., -4.]), i = -1, start = 0, end = 5, cutoff_point = 2
diag_tmp = array([0., 0., 0., 0., 0., 0.]), i = 1, start = 1, end = 6, cutoff_point = 3
diag_tmp = array([-6., -3., -1., -2.]), i = 3, start = 3, end = 6, cutoff_point = 4
diag_tmp = array([-4., -2.]), i = 5, start = 5, end = 6, cutoff_point = 5


In [87]:
another_arr_num.shape

(7, 9)